### ISSUE TITLE
Need Colors

### ISSUE THREAD

**Issue by BuildBeautiful4all** [B4BIPIN/GitGithubProject#2]
I think your list should contain some other things too, like this flow of git
 [**this is a link**](https://www.twitter.com)
![screenshot from 2018-08-08 19-36-36](https://user-images.githubusercontent.com/35399937/53945162-0068c500-40e7-11e9-84cb-078fbeda39f0.png)

**Comment by BuildBeautiful4all** [comment]
Please fix it @B4BIPIN right now..

**Comment by B4BIPIN** [comment]
Ok, this is a valid issue I will take care off.
